# Generated by Django 5.1.4 on 2025-01-03 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("LAB1", "Lab 1"),
                            ("LAB2", "Lab 2"),
                            ("LAB3", "Lab 3"),
                        ],
                        default="LAB1",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cabinet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cabinet_number", models.PositiveIntegerField(default=1)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabinets",
                        to="inventory.lab",
                    ),
                ),
            ],
            options={
                "unique_together": {("lab", "cabinet_number")},
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_number", models.PositiveIntegerField(default=1)),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelves",
                        to="inventory.cabinet",
                    ),
                ),
            ],
            options={
                "unique_together": {("cabinet", "shelf_number")},
            },
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.FloatField(help_text="in gram(g) or liter(L)")),
                ("description", models.TextField()),
                ("vendor", models.CharField(max_length=100)),
                ("hazard_information", models.TextField()),
                ("molecular_formula", models.CharField(max_length=100)),
                (
                    "reactivity_group",
                    models.CharField(
                        choices=[
                            ("Alkali", "Alkali"),
                            ("Alkaline Earth", "Alkaline Earth"),
                            ("Transition Metal", "Transition Metal"),
                            ("Lanthanide", "Lanthanide"),
                            ("Actinide", "Actinide"),
                            ("Metal", "Metal"),
                            ("Nonmetal", "Nonmetal"),
                            ("Halogen", "Halogen"),
                            ("Noble Gas", "Noble Gas"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "chemical_type",
                    models.CharField(
                        choices=[
                            ("Organic", "Organic"),
                            ("Inorganic", "Inorganic"),
                            ("Both", "Both"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "chemical_state",
                    models.CharField(
                        choices=[
                            ("Solid", "Solid"),
                            ("Liquid", "Liquid"),
                            ("Gas", "Gas"),
                            ("Plasma", "Plasma"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("expires", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chemical",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals",
                        to="inventory.shelf",
                    ),
                ),
            ],
        ),
    ]
